project_id = "ruzknsqkkbzyleqmmboc"

[functions.expire-claims]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false

[functions.notifications]
verify_jwt = false

[functions.premium-subscription]
verify_jwt = false
